### ISSUE TITLE
svn install fails for non-english LANG values

### ISSUE THREAD

**Issue by rwos** [easybiblabs/EasyBib_Core_Composer_Zf1ModuleInstaller#2]
https://github.com/easybiblabs/EasyBib_Core_Composer_Zf1ModuleInstaller/blob/master/src/EasyBib/Core/Composer/Zf1ModuleInstaller.php#L133

This check is always false for non-english environments (try with `LANG=de_DE` for example), since the exception message is localized.

**Comment by till** [comment]
@rwos I'll close this before 2017. ;))
